### ISSUE TITLE
Metadata should be a Hash, not an array

### ISSUE THREAD

**Issue by hrefhref** [pfefferle/wordpress-nodeinfo#1]
I spotted some invalid nodeinfo on the fediverse.network errors. It seems to be that your `metadata` field returns an empty array, while it should be an empty hash.

**Comment by hrefhref** [comment]
:heart: 

https://fediverse.network/wordpress :tada: 

edit/note: I think there's olders WordPress than your project on this list, am I wrong?

**Comment by pfefferle** [comment]
Nice 😍 

Might be, but I checked their pages and they all use this plugin.
