### ISSUE TITLE
info on file

### ISSUE THREAD

**Issue by Suitbert** [pfefferle/wordpress-nodeinfo#2]
I would be happy to see a few lines of info on the functionality of this plugin. After activated within Wordpress, I could not "see" nothing (as a non-developer ;-). In which directory should I find any config-file (config.json-file?)? Any details on the interaction with ActivityPub-Plugin? Thanks a lot for your help adding a short description.

**Comment by Suitbert** [comment]
![404s](https://user-images.githubusercontent.com/25386196/50376279-4eebe480-060b-11e9-8ea4-96ac9095b1b9.jpg)
After activating the plugin in compagnion with OStatus and ActivityPub I do get hundrets of 404s from all over the Fediverse. Any idea, how to get rid of those?

**Comment by pfefferle** [comment]
I think I answered your initial question: the plugin does not yet have any settings and you do not have to do anything except to install it :)

To your second question: I think this is because the networks try to get informations about your node... It is nothing I can handle with this a plugin... perhaps you/we should file an issue for fediverse.network... perhaps @hrefhref could help?

**Comment by hrefhref** [comment]
That is a side effet on how fediverse.network discoveres the instances data (before nodeinfo was implemented in almost all projects). I've been slowly working on a full revamp of its crawler to prioritize nodeinfo first (and other important changes) but that's not rolled out yet-- I hope mid-january.

**Comment by Suitbert** [comment]
All fine, thanks! I am only reporting what I have observed, not requesting any features ;-) But I am learning a lot, looking at those details. Thanks a lot for your great developement work!

**Comment by pfefferle** [comment]
@hrefhref thanks for your fast reply and I am curious about the upcoming changes!

**Comment by pfefferle** [comment]
@Suitbert so can I close this issue for now?

**Comment by Suitbert** [comment]
Thanks a lot!
