### ISSUE TITLE
nodeinfo rewrite via Wordpress doesn't seem to be working

### ISSUE THREAD

**Issue by techmagus** [pfefferle/wordpress-nodeinfo#3]
Hi,

Out of curiosity, I checked out my blogs in the fediverse.network tracker and found that it was marked as down and the checks all returned HTTP 301. I then checked `/.well-known/nodeinfo` and `/.well-known/x-nodeinfo2` as defined in the plugin (and ActivityPub plugin too) and indeed, Wordpress is throwing it back to the mainpage.

I checked the other plugins you made like WebFinger and host-meta and the rewrites for those are working: `/.well-known/host-meta.json` and `/.well-known/host-meta` for example. Checking via webfinger.net for the WebFinger, it works fine too.

The controller URL works fine for both nodeinfo and ActivityPub plugins:
```
index.php?rest_route=/nodeinfo/discovery
index.php?rest_route=/nodeinfo2/1.0
index.php?rest_route=/activitypub/1.0/nodeinfo/discovery
index.php?rest_route=/activitypub/1.0/nodeinfo2
```

Not sure why it isn't working but the other rewrites are fine. Anything I might have missed or something?

For now, my workaround is I added a rewrite in nginx for nodeinfo requests to direct to the nodeinfo plugin's rest_route. the-federation.info and fediverse.network are detecting the sites fine. (sample sites: gameshogun.xyz and snoworld.one )

**Comment by pfefferle** [comment]
It‘s hard for me to help in this case, because I do not really have experience with nginx and WordPress... Perhaps it is because of the mapping to API endpoints...

Do you have specific rules for WebFinger and host-meta?

**Comment by pfefferle** [comment]
BTW. if you have installed the nodeinfo plugin, you can ignore the nodeinfo endpoints of the ActivityPub plugin... I implemented a simple fallback into the AP plugin if someone have not installed the nodeinfo plugin.

**Comment by techmagus** [comment]
For the WebFinger and and host-meta, it's all being caught by this one:

```
location ~* /.well-known {
  allow all;
  try_files $uri $uri/ /index.php?$args;
}
```

But when it comes to nodeinfo2, I had to add this before the /.well-known catch-all (above):
```
location ~* /.well-known/nodeinfo {
  allow all;
  rewrite ^/.well-known/nodeinfo(.*)$ /index.php?rest_route=/nodeinfo/discovery last;
}
location ~* /.well-known/x-nodeinfo2 {
  allow all;
  rewrite ^/.well-known/x-nodeinfo2(.*)$ /index.php?rest_route=/nodeinfo2/1.0 last;
}
```

I tried other setups but none work. I'm not familiar with WP backend either. In any case, it isn't important. I just thought maybe it's on Wordpress's side or something. Adding a manual rewrite rule shouldn't be a problem (and there are redirect plugins for WP too in case a user doesn't have access to their server).

Have a wonderful new year!
