### ISSUE TITLE
NodeInfo 2.1 protocols field should be an array, not an object

### ISSUE THREAD

**Issue by braedon** [pfefferle/wordpress-nodeinfo#5]
In NodeInfo 2.x the `protocols` field is an array of protocols, not an object with `inbound` and `outbound` array fields like in NodeInfo 1.x.

This works correctly for the NodeInfo 2.0 endpoint, but the 2.1 endpoint returns a 1.x-style `protocols` object.

The offending line seems to be this code that applies the 2.x-style `protocols` to only version 2.0, and not 2.1: https://github.com/pfefferle/wordpress-nodeinfo/blob/5b754d798416373159eb5dc1ed0f8062c7ce3bfd/includes/class-nodeinfo.php#L70-L75

**Comment by pfefferle** [comment]
Thanks for the report! Should be fixed with V1.0.7
