### ISSUE TITLE
WooCommerce Customer Data Exposed 

### ISSUE THREAD

**Issue by d3cline** [pfefferle/wordpress-nodeinfo#6]
If you have a WooCommerce installation every customer's user data is searchable and exposed. This has to have a fix where only a given user class is automatically populated or exposed in any way. 

Also any customer who buys a product is now able to post as my instance. 

This is a serious breach of data security and should be a high priority. Under no circumstance should customer data be leaked this way or be possibly abused in this way. 

WooCommerce is a very popular plugin, without any warnings anyone installing `nodeinfo` plugin is now back dooring their customer database. And giving any attacker the ability to speak as the company. 

To reproduce simply install WooCommerce, and set up some customer accounts. Those accounts can now be found by federation search. 

The safe default must be admin or editor level or higher only. "normal customer accounts" users or "subscription" users can not be searchable or in ActivityPub whatsoever. Custom plugins which allow "wholesale" accounts must also be included.

**Comment by pfefferle** [comment]
The NodeInfo plugin only publishes the user count, nothing more! There is no way to publish anything, it is simply a statistics tool! I agree, that I should filter for specific users to not include woocommerce customers, but I see no security issue here!

**Comment by d3cline** [comment]
Which part of the ActivityPub suite links users to the federation? Which github does this need to be in? It wasn't particularly clear in the implementation .

**Comment by d3cline** [comment]
The `ActivityPub` plugin installs 4 other sub-plugins. This one appeared to be it based on the description

**Comment by d3cline** [comment]
https://github.com/pfefferle/wordpress-activitypub/issues/230

**Comment by pfefferle** [comment]
Ok, then it is an ActivityPub related issue. But the plugin does not publish usernames in an index or searchable way. You can guess usernames, that's true and this has to be fixed! Thanks for reporting this issue!
